# Generated by Django 6.0.2 on 2026-02-05 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=32)),
                ('source_no', models.CharField(blank=True, max_length=32, null=True)),
                ('category', models.CharField(max_length=64)),
                ('subtype', models.CharField(blank=True, max_length=64, null=True)),
                ('name', models.CharField(max_length=256)),
                ('name_kana', models.CharField(blank=True, max_length=256, null=True)),
                ('address', models.CharField(max_length=512)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('disaster_flags', models.JSONField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('synced_at', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['category'], name='shelters_pl_categor_6f8904_idx'), models.Index(fields=['name'], name='shelters_pl_name_84b353_idx')],
            },
        ),
    ]
